CLASS zcl_lab_19_lion_t100598 DEFINITION INHERITING FROM zcl_lab_18_animal_t100598
  PUBLIC

  CREATE PUBLIC .

  PUBLIC SECTION.
  METHODS WALK REDEFINITION.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_lab_19_lion_t100598 IMPLEMENTATION.
  METHOD walk.
   rv_walk = 'The lion walks'.
  ENDMETHOD.

ENDCLASS.
