CLASS zcl_lab_18_animal_t100598 DEFINITION
  PUBLIC

  CREATE PUBLIC .

  PUBLIC SECTION.
   METHODS WALK RETURNING VALUE(rv_walk) TYPE STRING.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_lab_18_animal_t100598 IMPLEMENTATION.
  METHOD walk.
   rv_walk = 'The animal walks'.
  ENDMETHOD.

ENDCLASS.
