CLASS zcl_lab_20_person_t100598 DEFINITION
  PUBLIC

  CREATE PUBLIC .

  PUBLIC SECTION.
   METHODS:  set_name FINAL IMPORTING iv_name TYPE STRING.
  PROTECTED SECTION.
   DATA: name TYPE STRING.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_20_person_t100598 IMPLEMENTATION.
  METHOD set_name.

  ENDMETHOD.

ENDCLASS.
