CLASS zcl_lab_13_view_t100598 DEFINITION
  PUBLIC
  CREATE PUBLIC .

  PUBLIC SECTION.

   METHODS constructor IMPORTING IV_VIEW_TYPE TYPE STRING.

  PROTECTED SECTION.
   DATA: VIEW_TYPE TYPE STRING,
         BOX       TYPE STRING.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_lab_13_view_t100598 IMPLEMENTATION.
  METHOD constructor.
   me->view_type = iv_view_type.
  ENDMETHOD.



ENDCLASS.
