CLASS zcl_lab_11_system_t100598 DEFINITION
  PUBLIC
  CREATE PUBLIC .

  PUBLIC SECTION.
  DATA: ARCHITECTURE TYPE STRING VALUE '64BITS'.
  METHODS get_architecture EXPORTING ev_architecture TYPE STRING.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_lab_11_system_t100598 IMPLEMENTATION.
  METHOD get_architecture.
  ev_architecture = me->ARCHITECTURE.
  ENDMETHOD.

ENDCLASS.

