CLASS zcl_lab_23_company_t100598 DEFINITION
  PUBLIC

  CREATE PUBLIC
  GLOBAL FRIENDS zcl_lab_24_partner_t100598.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
  DATA: CAPITAL TYPE STRING.
ENDCLASS.



CLASS zcl_lab_23_company_t100598 IMPLEMENTATION.
ENDCLASS.
