INTERFACE zif_lab_02_customer_t100598
  PUBLIC .
  TYPES: BEGIN OF TY_CUST_ADDRESS,
               FIRST_NAME TYPE STRING,
               LAST_NAME  TYPE STRING,
         END OF TY_CUST_ADDRESS.
  DATA pruebas TYPE STRING.
  METHODS GET_CUSTOMER IMPORTING IV_CUSTOMER_ID TYPE STRING
                       RETURNING VALUE(rv_type) TYPE TY_CUST_ADDRESS.


ENDINTERFACE.
